export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="powerlevel9k/powerlevel9k"
POWERLEVEL9K_MODE="nerdfont-complete"

POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_RPROMPT_ON_NEWLINE=true
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon dir dir_writable vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time root_indicator background_jobs time battery)
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%F{blue}\uf460%f "

POWERLEVEL9K_ROOT_ICON="\uF09C"
POWERLEVEL9K_TIME_FORMAT="%D{%H:%M}"

POWERLEVEL9K_BATTERY_VERBOSE=false

POWERLEVEL9K_OS_COMMAND_EXECUTION_TIME_BACKGROUND="242"
POWERLEVEL9K_OS_COMMAND_EXECUTION_TIME_FOREGROUND="248"

POWERLEVEL9K_OS_ICON_BACKGROUND="242"
POWERLEVEL9K_OS_ICON_FOREGROUND="248"

POWERLEVEL9K_BATTERY_LOW_BACKGROUND="242"
POWERLEVEL9K_BATTERY_LOW_FOREGROUND="210"
POWERLEVEL9K_BATTERY_CHARGING_BACKGROUND="242"
POWERLEVEL9K_BATTERY_CHARGING_FOREGROUND="222"
POWERLEVEL9K_BATTERY_CHARGED_BACKGROUND="242"
POWERLEVEL9K_BATTERY_CHARGED_FOREGROUND="222"
POWERLEVEL9K_BATTERY_DISCONNECTED_BACKGROUND="242"
POWERLEVEL9K_BATTERY_DISCONNECTED_FOREGROUND="248"

POWERLEVEL9K_STATUS_OK_BACKGROUND="242"
POWERLEVEL9K_STATUS_OK_FOREGROUND="215"
POWERLEVEL9K_STATUS_ERROR_BACKGROUND="242"
POWERLEVEL9K_STATUS_ERROR_FOREGROUND="210"

POWERLEVEL9K_DIR_HOME_BACKGROUND="110"
POWERLEVEL9K_DIR_HOME_FOREGROUND="236"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="110"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="236"
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="110"
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="236"

POWERLEVEL9K_SHORTEN_STRATEGY=truncate_from_right
POWERLEVEL9K_SHORTEN_DIR_LENGTH=3

POWERLEVEL9K_VCS_CLEAN_BACKGROUND='187'
POWERLEVEL9K_VCS_CLEAN_FOREGROUND='236'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='180'
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='236'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='174'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='236'

POWERLEVEL9K_VCS_GIT_ICON='\uF408 '
POWERLEVEL9K_VCS_GIT_GITHUB_ICON='\uF408 '

ZSH_DISABLE_COMPFIX=true

ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"

plugins=(
  aws
  git
  mercurial
  iterm2
  osx
  docker
  gradle
  brew
  npm
  vscode
  zsh-autosuggestions
  zsh-syntax-highlighting
  zsh-completions
  z
)

source $ZSH/oh-my-zsh.sh
unsetopt correct_all
setopt +o nomatch

if [ -f ~/.profile ]; then
  source ~/.profile
fi
